### ISSUE TITLE
Could we enable discussion tab ?

### ISSUE THREAD

**Issue by thibaultduponchelle** [melezhik/sparky#14]
This tab :
![disc0](https://user-images.githubusercontent.com/580360/103513202-6ac92880-4e6a-11eb-8254-e1f88613a315.png)

To be enabled in general settings from repo :
![disc1](https://user-images.githubusercontent.com/580360/103513213-70267300-4e6a-11eb-8455-53cf07e80c54.png)

**Comment by melezhik** [comment]
Done

**Comment by thibaultduponchelle** [comment]
Thank you :+1:
