### ISSUE TITLE
add option to disable bootstrap action

### ISSUE THREAD

**Issue by Spigell** [melezhik/sparky#2]
Здравствуйте. Неплохо было бы добавить такую опцию в sparky.yaml для того, чтобы клиент не бутстрапился. 
Это некритично, но не помешало бы.

**Comment by melezhik** [comment]
Приветствую! Вы хотите сделать эту настройку глобальной или для проекта?

**Comment by melezhik** [comment]
А все, вижу .... , для проекта ...

**Comment by Spigell** [comment]
Здравствуйте. Неакутально.
