### ISSUE TITLE
Change shebang to raku ?

### ISSUE THREAD

**Issue by thibaultduponchelle** [melezhik/sparky#36]

**Comment by melezhik** [comment]
@thibaultduponchelle sorry, if you tell me where do you want to change a shebang?

**Comment by thibaultduponchelle** [comment]
Why not put `#!/usr/bin/env raku` in sparkyd (contains `#!perl6`), sparky-runner.raku (contains no shebang) and sparky-web.raku (contains no shebang)

I propose https://github.com/melezhik/sparky/pull/44

**Comment by melezhik** [comment]
ahhh , sure! merged. and thanks! 👍
