### ISSUE TITLE
FTP for File Triggerring is confusing

### ISSUE THREAD

**Issue by thibaultduponchelle** [melezhik/sparky#45]
While I perfectly understand and love the feature, the acronym collision makes me uncomfortable.

Can we find something more around "file/dir watcher" or something else like "file creation" or "file event".

**Comment by melezhik** [comment]
From time to time I feel the same, let me think about better acronym / definition  ...

Maybe `FDD`? File Driven Deployment ... Feel free to provide yours. ... 

PS My only preference I'd like it to be short, acronym style ..

**Comment by melezhik** [comment]
~~FDP? File driven protocol  / file deployment protocol~~
~~FDDP? File driven deployment protocol~~

**Comment by thibaultduponchelle** [comment]
No, please, it means something not very nice in French

**Comment by melezhik** [comment]
sure, no problem ...

**Comment by melezhik** [comment]
STP - sparky triggering protocol

**Comment by thibaultduponchelle** [comment]
STP is ok 👌

**Comment by melezhik** [comment]
I've updated the doc
