### ISSUE TITLE
Sparky CI Web restarting too frequently

### ISSUE THREAD

**Issue by thibaultduponchelle** [melezhik/sparky#56]
Hello,

I feel like Sparky CI Web is restarting too frequently, like if it was watching logs and restarting on change:

![restart-sparky](https://user-images.githubusercontent.com/580360/156600920-752e3c86-49e3-4c16-997c-19f82f96f43c.png)

Is it normal?

**Comment by melezhik** [comment]
Hi! One of the possible reasons for that Sparky now runs as `cro run` - aka cro in development mode, any files changes under `/home/raku/test/Sparky/` would result in web app restart.

To privent Sparky web app from restarting one can use `cro.yml` file, `ignore` section:

https://github.com/melezhik/sparky/blob/master/.cro.yml#L5

As I can see you are using fresh Sparky docker image, right?

**Comment by melezhik** [comment]
Oh, I know, what is that, my fault )), it's sparkyd.log file that is changes constantly makes web app restart as well, I need to rebuild docker image to fix that ....

**Comment by melezhik** [comment]
As a temporary solution:

`docker exec -I -t sparky /bin/bash` and then edit cro.yml:


```yaml
ignore:
 - sparkyd.log
 ```

**Comment by thibaultduponchelle** [comment]
Fixed with latest Dockerfile, thank you!

**Comment by melezhik** [comment]
yeah, I also updated docker image on dockerhub

**Comment by melezhik** [comment]
thanks for continuing of  trying Sparky!
