### ISSUE TITLE
CI looks broken, project stuck in queue

### ISSUE THREAD

**Issue by pheix** [melezhik/sparky#58]
Project `git-pheix-core-perl6.git ` stuck in queue: https://sparky.sparrowhub.io/queue. Looks like no runners are available or smth like this.

Also I see last successful build about a week ago: https://sparky.sparrowhub.io/builds

**Comment by melezhik** [comment]
Hi! I will try to take a look tonight , thanks

**Comment by melezhik** [comment]
so, sparky job runner got stuck for some reasons and I had to kick it, should be good now

**Comment by melezhik** [comment]
https://ci.sparrowhub.io/report/3356 - OK now

**Comment by pheix** [comment]
closed!
