### ISSUE TITLE
Turn off/refine "flapper protection"

### ISSUE THREAD

**Issue by 2colours** [melezhik/sparky#59]
Hello,

in my use case, sparkyd runs forever and ever, as a pm2 task. From what I understand in the code, timeouts are never reset, and once they reach 5 occasions, the project is _permanently_ marked as a "flapper" which defeats the purpose of having the CI running 24/7 continuously.

I can imagine that there are timeouts for whatever reason but I generally don't even want that to make any difference, as long as there is any chance of recovering, whether that's 5 minutes later, 2 hours later or a couple of days later. I think there should be either a way to turn this feature off completely, or at least the timeouts should wear off. If every second attempt times out, that's still okay. If 5 attempts time out in a row, even that might be okay, depending on the timing circumstances. In any case, only massive bursts of timeouts should be considered.

**Comment by melezhik** [comment]
@2colours Sorry for late reply, I guess it's possible, fix seems to be pretty simple - https://github.com/melezhik/sparky/blob/master/bin/sparkyd#L38

**Comment by melezhik** [comment]
done - https://github.com/melezhik/sparky#flappers-protection-mechanism
