### ISSUE TITLE
Вопрос насчет оформления в админке sparky

### ISSUE THREAD

**Issue by Spigell** [melezhik/sparky#6]
Здравствуйте. А можете ли описать возможность смены темы в sparky. Насколько я понимаю, достаточно забрать с bootswatch bootstrap.min.css и положить public/css/bootstrap.min.css? Надо ли еще проводить какие-то операции с CSS? Можно ли использовать bootstrap.css вместо bootstrap.min.css?

**Comment by melezhik** [comment]
Приветствую! Все примерно так как вы описали. Сейчас что бы сменить css стили twitter bootstrap в sparky я делаю так:

```
$ bash ./utils/update-skin.bash $skin-id
```

Например `bash ./utils/update-skin.bash cosmo`

Список доступных стилей/тем - тут - https://bootswatch.com/


После этого нужно перезапустить web UI sparky:

```
$ perl6 bin/sparky-web.pl6
```

> Можно ли использовать bootstrap.css вместо bootstrap.min.css?

Мой скрипт скачивает именно эти два файла ( bootstrap, bootstrap.min ) - не уверен, что можно один вместо другого использовать, если честно с этим не разбирался, надо читать в док-ии по twiter bootstrap наверное

**Comment by Spigell** [comment]
Спасибо! Получается, что bootstrap.css и его меньшая версия от темы, а файлик bootstrap-theme для корректировки. Так?

**Comment by melezhik** [comment]
Видимо да. Я не уверен, зачем нужен файл bootstrap-theme, можно будет проверить, что будет, если его убрать ...

**Comment by Spigell** [comment]
bootstrap-theme нужен для переопределения темы. На текущий момент, он немного переопределяет цвет панели, где написано "Recents builds" ( делает более синим ) и еще кое-что по мелочи. В целом, если хочется поменять тему, то надо удалять его или редактировать под свои нужны.

Для докера я использую такую структуру для изменения стиля.
```
bash 'curl -s -f https://bootswatch.com/3/united/bootstrap.min.css -o /root/sparky/public/css/bootstrap.min.css';

bash 'rm -rfv /root/sparky/public/css/bootstrap-theme.min.css';


```
