### ISSUE TITLE
Problem loading configs hash

### ISSUE THREAD

**Issue by thibaultduponchelle** [melezhik/sparky#7]
Hello,

`raku bin/sparky-runner.raku --dir=~/.sparky/projects/hello/` is not working because the `~` is not translated to absolute path at this [line](https://github.com/melezhik/sparky/blob/master/bin/sparky-runner.raku#L281).

You end up with this empty configuration because we never enter the if block : 
`merged sparrowdo configuration: { }`

**Comment by melezhik** [comment]
sparky runner relies on Raku's main args parser, which to my knowledge does not provide shell expansion - https://github.com/melezhik/sparky/blob/master/bin/sparky-runner.raku#L15 

maybe we could think about alternative that supports the one?

**Comment by thibaultduponchelle** [comment]
I agree, but at least README has to be fixed

**Comment by melezhik** [comment]
Does this commit will be enough? Or it worth to mention in the doc `main` limitation on  shell expansion as well?

**Comment by thibaultduponchelle** [comment]
Prefect ! 👍 thank you
