### ISSUE TITLE
Реализация страницы с проектами

### ISSUE THREAD

**Issue by spigell** [melezhik/sparky#8]
Здравствуйте.  Давно думаю, что надо добавить в sparky web главную страницу со списком всех проектов. например такую табличку с такой шапкой.

Проект |время последнего прогона| результат последнего прогона| что-то еще |

Есть мысль, что надо сделать еще одну табличку project, откуда и будут браться данные для страницы.

Вот тут вопрос: Как обновлять эту таблицу? Есть идея, что надо раз в несколько минут смотреть какие каталоге есть на диске и сравнивать с тем что есть в бд. Если чего то нет - то добавлять/апдейтить.

Что вы думаете насчет всего этого?

**Comment by spigell** [comment]
Доброго времени суток. Да, можно это так назвать. 
Страницу с билдами оставить - просто ограничить количество показываемых билдов

**Comment by melezhik** [comment]
Приветствую! 
Попробуйте  обновиться с github, добавил заявленную фичу.

**Comment by melezhik** [comment]
> Вот тут вопрос: Как обновлять эту таблицу? Есть идея, что надо раз в несколько минут смотреть какие каталоге есть на диске и сравнивать с тем что есть в бд. Если чего то нет - то добавлять/апдейтить.


Пока реализовал по простому, просто делаю выборку из таблицы `builds`, с группировкой по проектам и агрегатной функцией `max(id)` , которая дает последний билд по проекту ... очевидно, что при этом проекты, у которых не было еще ни одного билда, показываться не будут ...

**Comment by spigell** [comment]
Здравствуйте. Посмотрю. Спасибо.

**Comment by melezhik** [comment]
released at version 0.0.25
