### ISSUE TITLE
Spin up a test Sparky instance for dog fooding

### ISSUE THREAD

**Issue by melezhik** [melezhik/sparky#9]
I'd be good to have one with public IP. http://rakudist.raku.org/sparky/ should be considered booked for Raku community purposes and is not good candidate if users want just to play with web hooks or other test requests ...

I have free tier aws account which expires pretty soon, any ideas where we could have  (free?) resources? We need something 2-4GB RAM and 2-4 CPU core setup. 

cc @thibaultduponchelle

**Comment by melezhik** [comment]
http://161.35.142.50/

**Comment by melezhik** [comment]
cc @thibaultduponchelle

**Comment by thibaultduponchelle** [comment]
Cool ! A new playground ! 😃

**Comment by thibaultduponchelle** [comment]
Temporary ?

**Comment by melezhik** [comment]
Let's see. It's digital ocean droplet, I have 30-60 days trail, but maybe I'll keep afterward if it costs me something 20-40 $USD per month, why not ... 🤔

**Comment by melezhik** [comment]
but it should be pretty fast. 8 GB / 4 Core CPU. I am going to have all the sparky jobs under `--localhost` with `sudo` is not allowed of course 😄

**Comment by melezhik** [comment]
I put all the scenarios for play ground here - https://github.com/melezhik/sparky-playground , they are automatically updated by this [job](http://161.35.142.50/project/sparky-update).

**Comment by thibaultduponchelle** [comment]
Then you only had to setup one first project, and it acts as a sort of "scanning" (not really)  or "registration" for various jobs and scm, if I understand correctly.

Very nice trick :muscle:

**Comment by melezhik** [comment]
Exactly! In a spirit of Sparky. You can basically can do all the development in GH UI, hehe 😄

**Comment by melezhik** [comment]
the instance no longer exists
